[package]
name = "crane9-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "crane9"
path = "src/crane9.rs"

[[bin]]
name = "crane10"
path = "src/crane10.rs"