[package]
name = "pairs7-8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pairs7"
path = "src/pairs7.rs"

[[bin]]
name = "pairs8"
path = "src/pairs8.rs"